### ISSUE TITLE
css/elevation.css is incorrect

### ISSUE THREAD

**Issue by shadow-identity** [material-foundation/material-tokens#12]
`elevation` classes has incorrect values, for example:
```css
.elevation-0 {
  box-shadow: var(--md-sys-elevation-level0);
}
```
will not work because there is no `--md-sys-elevation-level0` defined in the repo.

It makes all the elevation settings to be broken.
